s = input()
s = s.replace('0', 'sıfır')
s = s.replace('1', 'bir')
s = s.replace('2', 'iki')
s = s.replace('3', 'üç')
s = s.replace('4', 'dört')
s = s.replace('5', 'beş')
s = s.replace('6', 'altı')
s = s.replace('7', 'yedi')
s = s.replace('8', 'sekiz')
s = s.replace('9', 'dokuz')
print(s)
