name: UploadServer
on:
  push:
    branches:
      - 'main'
env:
  ssh_key: ${{ secrets.SSH_KEY }}
  ip: ${{ secrets.IP }}
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: upload
        run: | 
          cat "${{ secrets.SSH_KEY }}" > /tmp/tempkey
          chmod 600 /tmp/tempkey
          ssh -i /tmp/tempkey root@${{ secrets.IP }} "cd isar; sudo pkill 'uvicorn'; git pull; ./deploy.sh"
